name: "Run Devil Run"
description: "专注润学，共同建设地址: https://github.com/jingwendom/run"

url: 'jingwendom.github.io/run' 
baseurl: 'jingwendom.github.io/run'

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

